### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by EdoaXYZ** [dariowouters/ts-map#1]
I've seen that the program requires some files but I don't know exactly which one and how to get them.
Also, does it works with the new Italia DLC?

**Comment by dariowouters** [comment]
Thanks, I totally forgot I hadn't added those files yet.
I've added the required files and the readme.

I'll write a more clear readme later but I think you should be able to figure out what files you all need from the current one.

And yes, all current map DLC's are supported.

**Comment by EdoaXYZ** [comment]
Thanks, now it works 👍 
It's faster than [this]( https://github.com/nlhans/ets2-map) and it includes a lot of interesting things about prefabs but it doesn't include navigation system.
Good job!
