### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by DubStepMad** [dariowouters/ts-map#17]
Hello,

I complied the source as release but I get the following issue:

![image](https://user-images.githubusercontent.com/13799856/94342754-157bb080-000b-11eb-92ec-bc9a46643080.png)

**Comment by shardick** [comment]
You have to run TsMap.Canvas not TsMap, that's a library and cannot be ran alongside.

**Comment by DubStepMad** [comment]
@shardick Ignore me as I was being silly.
