### ISSUE TITLE
1.45 beta problem?

### ISSUE THREAD

**Issue by Kycko** [dariowouters/ts-map#29]
I don't know C language, so I can only say for you the program is not working/compiling...
I've successfully compiled and used the current program with game version 1.44, but it doesn't run with 1.45 beta.

**Comment by shardick** [comment]
Looks like there is a new Item:

` Unknown Type: 1041248412 in sec-0008+0006.base @ 273`

and then, there is an expection in `MemoryHelper.ReadSingle`

**Comment by dariowouters** [comment]
Thanks for letting me know, the latest commit to the develop branch now supports the 1.45 Open Beta.

**Comment by Kycko** [comment]
@dariowouters the map now loads but there's no road to Werlte. 🤔 Hannover from 1.45 is OK, it's updated.
Krone Trailer Pack is installed in my system and I see this road in the game.

![image](https://user-images.githubusercontent.com/12460263/177208160-88b8c41b-530c-46bb-8755-c2caa4f31ac9.png)

**Comment by dariowouters** [comment]
Ah right, forgot that that area would be DLC guarded, now there's a problem with me just using a number for DLC guards.
So when you set the DLC guard count for ETS2 to 15, which is required for the Krone area to be loaded, the roads to the Heart of Russia DLC area are also loaded.
![image](https://user-images.githubusercontent.com/5845806/177213170-5ddf890c-42e7-468e-9317-06a4d28da5c8.png)

Again, thanks for letting me know, it's something I'll look into. Probably make it so specific DLC guards can be enabled/disabled by the user. But this won't be done right away.

So in the mean time you can set the `Ets2DlcGuardCount` in `TsMap/Common/Consts.cs` to 15. (but then you will have unfinished roads near Russia)

**Comment by dariowouters** [comment]
With the latest commit it's possible to enable and disable specific DLC guards in the 'view' menu, disabling a DLC guard will hide all items that have that guard set on them.

By default it has every guard enabled except the "Heart of Russia" DLC guards for ETS2.
So the Krone area will show up but the unfinished roads near the "Heart of Russia" DLC will not.

For ATS the DLC guards for Montana and Texas are disabled by default.

**Comment by shardick** [comment]
Confirm it's working fine on 1.45 with DLC guards switch off.
As always, thanks for everything Dario

**Comment by Kycko** [comment]
I've noticed 2 minor problems with the fresh version from develop branch:
- I see the hidden road to the east from Saint-Petersburg with default DLC guards (13 and 14 are disabled);
- Werlte city name is still on the map when I disable Krone DLC guard. I think it must not be shown. 🤔
![image](https://user-images.githubusercontent.com/12460263/178161656-7ab10584-65ff-4c9d-8d21-2a8a9a2b6a14.png)

**Comment by dariowouters** [comment]
The hidden road is an SCS issue, the item does not have a DLC guard set on it. The only reason you don't see it in the in-game map is because it's a secret road and so it is hidden until you drive over it.
![image](https://user-images.githubusercontent.com/5845806/178163965-3eb3ae3e-4a33-4861-8257-4993986b19e6.png)

As for Werlte, city items do not have a DLC guard option, so it will always show if you have the Krone DLC. As this application currently does not have an option to fully disable a DLC, if you want to not show the city you'll have to temporarily remove the DLC file.
