### ISSUE TITLE
Some clarifications about TsRoadSideItems

### ISSUE THREAD

**Issue by edoaxyz** [dariowouters/ts-map#3]
I've done some research on TsRoadSideItems and I've found some interesting things. Maybe these could be useless in project and will slow down the entire program but I propose you to put them in the associated template file for 010 Editor.

First of all, if you want to run all these stuff you need to add in the `ScsHash.cs` file the function that permits to convert a token to a string.

Template contains a 72 byte array called as `padding` actually contains data. If the item is a road sign for navigation like the one in the picture below, there will be some text and pictures for destinations that can be showed as a .dds file contained in `/material/overlay`. The name of the files can be found (encoded) inside 9 unsigned quad variables that decoded using the TokenToString function previously mentioned return the name of the files ( prefix `city_` or `road_` must be added before name depending to the index of variable. The structure of those variables is:
 - first sign
   - 8 byte number (road icon)
   - 8 byte number (primary road destination - as text)
   - 8 byte number (secondary road destination - as text)
 - second sign
   - 8 byte number (road icon)
   - 8 byte number (primary road destination - as text)
   - 8 byte number (secondary road destination - as text)
- third sign
   - 8 byte number (road icon)
   - 8 byte number (primary road destination - as text)
   - 8 byte number (secondary road destination - as text)

![immagine](https://user-images.githubusercontent.com/17519322/45919620-7d391700-be98-11e8-9fe7-87463c61f4d0.png)

Next, in the same template there's a variable called `m_some_model_id` which, if encoded with the same function as before, contains the unit name of the sign, without the prefix `sign.`. This can be used in `/def/world/sign.sii` for getting the relative information.

And, the variable called `m_some_uid` contains the same uid that the item's relative node has. It is strange because it hasn't any sense, but it's there.

**Comment by dariowouters** [comment]
Thanks.

I probably should've named it something different than padding, but since only some signs have that data in the .base files, I didn't spend any time on it because this project (currently) doesn't need it.

But I added it to the template and I also added the hash decode (token -> string) function to the template files.
So if you add `<read=token_to_string>` at the end of a variable it will decode the token to a string automatically (I already added it to most of them).
