### ISSUE TITLE
Reading navigation data (.navcache)

### ISSUE THREAD

**Issue by cerus** [dariowouters/ts-map#30]
Hey there! I'm currently working on a ETS map viewer and your ts-map project has been really helpful so far, thanks a lot for this.

I would like to add navigation / route generation to my map, but that's easier said than done. One way of doing this would be to export the roads and prefabs so that I can run some sort of algorithm to generate a route, but I have absolutely no idea how I should do that. Another way would be to work with the navigation cache of ETS2. Unfortunately the .navcache format is not documented anywhere.

I've tried to reverse engineer the format myself, but I'm already stuck. I've only been able to decipher the first part of what I assume to be the header (4 bytes magic value (`NAVC`) followed by 4 bytes version (`0x01`)).

It seems like you have a bit more experience with reverse engineering file formats than I do judging by this repository. Would you be able to help with this? I understand if that's completely out of scope.

The navigation cache can be found in `Documents\Euro Truck Simulator 2\cache\<profile id>.navcache`. I can send you my own navcache if needed.

Thank you!

**Comment by dariowouters** [comment]
I took a quick look at the navcache files but couldn't really see anything familiar. It would probably require reverse engineering the game's exe to figure out how it creates those files.

But I don't think you really need that file, the nodes in the .base files contain a previous and next item UID, so you should be able to path through from point a to point b using those. As for prefabs with more than 2 nodes you might have to check the .ppd documentation for what values to use to get the path to an end node.

You could take a look at the code of either of these projects as they both have a navigation feature:
- The original project that this one is based on: https://github.com/nlhans/ets2-map
- A fork of this project: https://github.com/edoaxyz/ts-map

**Comment by cerus** [comment]
Thank you so much for pointing me in this direction! I was able to update edoaxyz's fork and get it running.

I'll close this issue for now. Again, thank you!

**Comment by shardick** [comment]
Is nice they replied. out of curiosity, to which email you write to?

wonder how others g_*_debug exist :D

**Comment by cerus** [comment]
> Is nice they replied. out of curiosity, to which email you write to?

I wrote to `contribution@scssoft.com` which is meant for modding wiki contribution requests and not for modding questions, but it was the only email address I could find :D

**Comment by meatlayer** [comment]
> Thank you so much for pointing me in this direction! I was able to update edoaxyz's fork and get it running.
> 
> I'll close this issue for now. Again, thank you!

Do you plan to publish a your fork? It would be interesting to see a working version.

**Comment by cerus** [comment]
> > Thank you so much for pointing me in this direction! I was able to update edoaxyz's fork and get it running.
> > I'll close this issue for now. Again, thank you!
> 
> Do you plan to publish a your fork? It would be interesting to see a working version.

It's very messy, but I can create a repository for it later today. :)

**Comment by cerus** [comment]
I've published the fork: https://github.com/Spedcord/ts-map

As I said it's very messy and not user friendly. It's also not perfect. Feel free to modify.

cc @meatlayer
