### ISSUE TITLE
Problem on place for landmark icon

### ISSUE THREAD

**Issue by JAGFx** [dariowouters/ts-map#31]
With our latest version, I think there are a little problem on the place for landmark icon

As you can see, the landmark icon is placed nowhere.

![image](https://user-images.githubusercontent.com/12508080/201531313-98147a9a-5ff1-4ce3-9a6b-3455130be9c6.png)

I use the latest version of ETS (1.46).

**Comment by dariowouters** [comment]
No, that is where the icon should be. If you check the in-game map it's in the same place.
![image](https://user-images.githubusercontent.com/5845806/201538819-c18042e4-2659-41a7-bf69-83b1f9f40c3a.png)
