### ISSUE TITLE
Prefab polygons drawn with wrong z-index

### ISSUE THREAD

**Issue by truckermudgeon** [dariowouters/ts-map#33]
It looks like there's an issue with some prefab polys not rendering correctly. In the ATS map editor, near Truckee, California I see:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/121829201/224234196-b2b784aa-7f25-42e6-b0d6-4b35e61179c5.png">

But in `ts-map`, I see:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/121829201/224234478-c17e4e74-d57c-4dd6-a4a0-953a0e27254a.png">

I think it has something to do with [this ZIndex assignment](https://github.com/dariowouters/ts-map/blob/d5c275a/TsMap/TsMapRenderer.cs#L220):

```ts
if ((colorFlag & 0x02) != 0) fillColor = palette.PrefabLight;
else if ((colorFlag & 0x04) != 0) fillColor = palette.PrefabDark;
else if ((colorFlag & 0x08) != 0) fillColor = palette.PrefabGreen;
// else fillColor = _palette.Error; // Unknown

var prefabLook = new TsPrefabPolyLook(polyPoints.Values.ToList())
{
    ZIndex = ((colorFlag & 0x01) != 0) ? 3 : 2,  // <= incorrect?
```

Possible fixes might be:

```ts
    // assumes PrefabLight is always the "background" of a prefab area
    ZIndex = (fillColor == palette.PrefabLight) ? 2 : 3, 
```

or maybe

```ts
    // this check matches the explicit fillColor assignment in line 213
    ZIndex = ((colorFlag & 0x02) != 0) ? 2 : 3, 
```

Either of those changes leads to `ts-map` rendering:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/121829201/224236316-866cec7d-5468-412b-b6df-a587aaf411cb.png">

Hope this helps!

Lastly: I discovered `ts-map` while doing some research for my own mapping project. `ts-map` is amazing; the code and the `docs` folder have been a very valuable reference. Thanks for you time and effort working on it!

**Comment by dariowouters** [comment]
Thanks, no idea how I've never noticed that before.

Draw order for polygon parts of prefabs and map areas should now be correct.
