### ISSUE TITLE
Support for 1.48.5 + West Balkans DLC

### ISSUE THREAD

**Issue by dowmeister** [dariowouters/ts-map#39]
Hey Dario,
hope you are good.

Application crashes on parsing 1.48.5 files - Tested on master and develop, with ETS2 with West Balkans DLC

seems the `Sector.Version` of `TsCompanyItem` is 900

For your information, if this could spare some time, the new DLCGuards are

```
 new DlcGuard("dlc_blkw", 16, false),
 new DlcGuard("dlc_blkw_and_east", 17, false),
 new DlcGuard("dlc_blkw_and_blke", 18, false),
 new DlcGuard("dlc_feldbinder", 19, false)
```

and for ATS + Oklahoma:

```
new DlcGuard("dlc_ok", 25),
new DlcGuard("dlc_ok_and_co", 26),
new DlcGuard("dlc_ok_and_nm", 26),
new DlcGuard("dlc_ok_and_tx", 27),
new DlcGuard("dlc_ks", 28),
```

How fix this? what is the magic behind it? :)

Thanks

**Comment by dariowouters** [comment]
Thanks, added the DLC guards, and the crash was caused by the change to the companies pickup/drop off location changes.

**Comment by dowmeister** [comment]
Works perfectly, thanks
