### ISSUE TITLE
Some hidden roads are showed in ATS - Oregon

### ISSUE THREAD

**Issue by edoaxyz** [dariowouters/ts-map#4]
Some hidden roads between Pendleton and The Dalles are displayed in map.
![immagine](https://user-images.githubusercontent.com/17519322/46627733-b2519480-cb3b-11e8-8e06-df51e4a3b067.png)
![immagine](https://user-images.githubusercontent.com/17519322/46627836-052b4c00-cb3c-11e8-8342-e8a8370920c4.png)

**Comment by dariowouters** [comment]
Most roads are gone except this tiny part of a weigh station.
![tsmap](https://user-images.githubusercontent.com/5845806/46632434-f009e980-cb4a-11e8-881c-818eca635bb1.png)

But this is also there on the actual in-game map (right above the cursor) : 
![atsmap](https://user-images.githubusercontent.com/5845806/46632480-1465c600-cb4b-11e8-8fc5-105b571b1cab.png)

So I'm just leaving it like this.
