### ISSUE TITLE
Issue while converting values from game coords to pixels

### ISSUE THREAD

**Issue by LouisVenhoff** [dariowouters/ts-map#42]
Hello, 
I have 256px * 256px ETS TileMap which is displayed in Leaflet.js.
I generated the map with ts-map.

To calculate the coordiantes i use this function:

```javascript
const calculateCoords = (gameX:number, gameY:number) => 
    {
        const x1:number = tileInfo.x1;
        const x2:number = tileInfo.x2;
        const y1:number = tileInfo.y1;
        const y2:number = tileInfo.y2;
        
        const MAX_X:number = 256 * 256;
        const MAX_Y:number = 256 * 256;

        const xtot = x2 - x1; // Total X length
            const ytot = y2 - y1; // Total Y length

            const xrel = (gameX - x1) / xtot; // The fraction where the X is (between 0 and 1, 0 being fully left, 1 being fully right)
            const yrel = (gameY - y1) / ytot; // The fraction where the Y is

        setPosition([xrel * MAX_X, (yrel*MAX_Y)]);
    }
```

The problem is, that the my map is 256px but the calculated values are much to big.
When i use a correction Value which i calculate with 256/MAX_X the marker is on the map.
In this case the X value is correct, but the y value is not right.
The marker on the map is is displayed is unter the position i want to target.

Have anyone a solution to calculate the positions correctly or can anyone find the bug in my code ?

Thanks

**Comment by meatlayer** [comment]
There is a working example here
https://github.com/dariowouters/ts-map/issues/16#issuecomment-1176767040

**Comment by LouisVenhoff** [comment]
@meatlayer Thanks for the answer. I think my function ist implemented this way.

Calculation with example values 

I can set the marker on the map 256px x 256px.

My calculation of the Max values: 256×256 =65536.

If relX × Max = x

0.56 × 65536 = 36700.16

This value ist "out of coordonates" for my map.

Where is my fallancy here ?

**Comment by meatlayer** [comment]
You need to take data from the TileMapInfo.json for the correct conversion of coordinates from the game world to pixel coordinates on the leaflet.js map. Here is a ready-made 100% worked function for convert coords:

```
function game_coord_to_image(xx, yy) {
	var MAX_X = 131072; //padding in ts-map 384px
	var MAX_Y = 131072; //padding in ts-map 384px
	
	// Values from TileMapInfo.json
	const x1 = -94505.8047;
	const x2 = 79254.13;
	const y1 = -80093.17;
	const y2 = 93666.7656;

	const xtot = x2 - x1; // Total X length
	const ytot = y2 - y1; // Total Y length

	const xrel = (xx - x1) / xtot; // The fraction where the X is (between 0 and 1, 0 being fully left, 1 being fully right)
	const yrel = (yy - y1) / ytot; // The fraction where the Y is

	return [
		xrel * MAX_X, // Where X actually is, so multiplied the actual width
		yrel * MAX_Y // Where Y actually is, only Y is inverted
	];
}
```
The example above is for the map size for 131x131 Kpx / zoom 8 / padding 384
Just adapt it to your needs and enjoy leaflet's work.

**Comment by LouisVenhoff** [comment]
Thank you @meatlayer. I will check if it works  :)

**Comment by LouisVenhoff** [comment]
I found the issue, the code works pretty. 
But there is an error in my coordinate source.

Thank you for your help :)
