### ISSUE TITLE
Compatibility with 1.36 Open Beta (Corsica)

### ISSUE THREAD

**Issue by shardick** [dariowouters/ts-map#7]
Hi, 
i'm trying to open the map for ETS2 with 1.36 open beta but crashes on parsins TsRoadItem, TsTrigger and some prefabs.

There is any way to understand how make it compatible with latest version? If i can help actively, i can send a PR.

Thanks

**Comment by dariowouters** [comment]
Support for the 1.36 (beta) version is currently only supported in the [develop branch](https://github.com/dariowouters/ts-map/tree/develop). I'll push this to master when 1.36 is out of beta and it's clear there are no more bugs.

The develop branch version works for both ATS & ETS2.

**Comment by shardick** [comment]
ah sorry. didn't view the commit on develop branch.

thanks for your work!
