### ISSUE TITLE
Various errors generating tiles (develop branch)

### ISSUE THREAD

**Issue by shardick** [dariowouters/ts-map#8]
Hi,
i'm having various and strange errors generating map tiles with different configurations, generating for ATS 1.36 (all dlcs):

- Tile size 512 and map padding 400: randomly fires "Parameter not valid" in `var bitmap = new Bitmap(tileSize, tileSize);` (TsMapCanvas.cs line 91)
- Tile size 256 and map padding 500: "Generic Error in GDI+" at `bitmap.Save($"{exportPath}/Tiles/{z}/{x}/{y}.png", ImageFormat.Png);` (TsMapCanvas.cs line 98), example Tiles\8\15 tile 1 . Generated tile remain corrupted

![image](https://user-images.githubusercontent.com/518905/68424166-b66b3e00-01a3-11ea-9f3b-7bf7ff56ddfc.png)

Master branch, instead, no errors.

(as usual, great job!)

**Comment by dariowouters** [comment]
I can't seem to reproduce either of those errors at any tileSize or mapPadding, what zoom levels are you using? Have you made any other changes?

**Comment by dariowouters** [comment]
That should hopefully fix the crashes.

**Comment by shardick** [comment]
Min zoom 1, max zoom 0. Other changes were only in palettes. 

Thanks, i will try as soon as possible.

Btw, i can contribute to the project? I would add new options to tiles generation, palette management e other little things. Everytime i have to merge my local version

**Comment by shardick** [comment]
Tiles generated but with a error breakpointed "Managed Debugging Assistant 'ContextSwitchDeadlock' ", with a continue tiles generation goes ahead and terminates correctly.

**Comment by dariowouters** [comment]
It's because I'm currently doing all the generating of tiles on the UI thread, which is something you shouldn't really do because it will look like the program freezes, and Visual Studio breaks thinking it's frozen. You can disable this in VS in `Debug > Windows > Exception Settings` and then `Managed debugging assistants > ContextSwitchDeadlock`

That said I should probably just move the generating to a background thread.

**Comment by shardick** [comment]
Yeah! I know. was just for information, with previous versions I hadn't this warning.

I have add map palette editor and general changes to settings management. I can open a PR?

**Comment by dariowouters** [comment]
Yeah sure that's fine.

**Comment by shardick** [comment]
PR sent.

i'm closing this. 

Thanks
